// ndrchst edge Worker — serves the client-distribution surface from the R2
// bucket so the residential box stays out of the per-client hot path. The
// surface is entirely static now (no box origin to proxy to).
//
// The whole surface lives on ONE host (play.ndrchst.com); apex + www 301 here
// (see fetch()), so every route below is served from that single origin.
//
// STATIC (from R2 bucket DL):
//   GET /            → index.html    (landing — generated by the box, publish.py)
//   GET /play        → play.html     (server list — generated by the box)
//   GET /client/<sid>/<...> → client/<sid>/<...>   (config, manifest, client.zip,
//                                                 mods/index.json, mods/<jar>)
//   GET /client/latest.json + binaries → client self-update artifacts
//   GET /<other>     → <other>       (servers.json, game/*, …)
//   GET /healthz     → "ok"
//
// Object Content-Type / Cache-Control come from what the box stored on
// upload (writeHttpMetadata), so the box controls freshness centrally.

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    // One canonical host: play.ndrchst.com. apex + www 301 here, preserving
    // path and query (so e.g. www.ndrchst.com/play → play.ndrchst.com/play).
    if (url.hostname === "ndrchst.com" || url.hostname === "www.ndrchst.com") {
      return Response.redirect("https://play.ndrchst.com" + path + url.search, 301);
    }

    if (path === "/healthz") {
      return new Response("ok", { headers: { "content-type": "text/plain" } });
    }

    // Everything is a static asset from R2 — read-only.
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method Not Allowed", { status: 405 });
    }

    let key;
    if (path === "/") {
      key = "index.html";   // root of the one host is the marketing landing
    } else if (path === "/play") {
      key = "play.html";    // the player / app page
    } else if (path === "/favicon.ico") {
      key = "game/favicon.png";   // browsers auto-request /favicon.ico
    } else {
      key = decodeURIComponent(path.replace(/^\/+/, ""));
    }
    if (!key) return notFound();

    const range = request.headers.get("range");
    const obj = await env.DL.get(key, range ? { range: parseRange(range) } : undefined);
    if (!obj) return notFound();

    const headers = new Headers();
    obj.writeHttpMetadata(headers);
    headers.set("etag", obj.httpEtag);
    if (!headers.has("cache-control")) headers.set("cache-control", "no-cache");

    if (range && obj.range) {
      const len = obj.size;
      const start = obj.range.offset ?? 0;
      const end = start + (obj.range.length ?? len - start) - 1;
      headers.set("content-range", `bytes ${start}-${end}/${len}`);
      headers.set("accept-ranges", "bytes");
      return new Response(request.method === "HEAD" ? null : obj.body, {
        status: 206,
        headers,
      });
    }
    return new Response(request.method === "HEAD" ? null : obj.body, { headers });
  },
};

function notFound() {
  const body = `<!doctype html><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1"><title>404 — ndrchst</title>
<style>html{height:100%}body{margin:0;min-height:100%;display:flex;flex-direction:column;
align-items:center;justify-content:center;gap:1.1rem;text-align:center;padding:2rem;
background:#0a0613;color:#f4f0ff;font-family:'Space Grotesk',system-ui,sans-serif}
h1{font-size:5rem;margin:0;color:#14f195;letter-spacing:.05em}p{margin:0;color:#a99fc7}
a{color:#f4f0ff;text-decoration:none;border:1px solid #2a2150;padding:.6rem 1.2rem;
border-radius:.6rem}a:hover{border-color:#14f195}</style>
<h1>404</h1><p>This page drifted into the End.</p><a href="/">Back to ndrchst</a>`;
  return new Response(body, {
    status: 404,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

function parseRange(header) {
  // Single "bytes=start-end" range → R2 get options.
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (!m) return undefined;
  const [, s, e] = m;
  if (s === "" && e === "") return undefined;
  if (s === "") return { suffix: Number(e) };
  const opt = { offset: Number(s) };
  if (e !== "") opt.length = Number(e) - Number(s) + 1;
  return opt;
}
