"""Build-time config for a pilot drop. Generated by ndrchst's pilot
bundle builder per-server; edit only if you know what you're doing.

Required fields:
  APP_NAME           — displayed in the GUI title bar
  SERVER_HOST/PORT   — fallback dial target if TUNNEL_HOSTNAME isn't set
  MC_VERSION         — vanilla MC version, e.g. "1.21.1"
  DEFAULT_USERNAME   — initial username in the GUI field

Optional fields (modpack + tunnel support):
  NEOFORGE_VERSION   — pin the NeoForge build, e.g. "21.1.228"
  MODPACK_URL        — CurseForge client-pack zip URL to install
  TUNNEL_HOSTNAME    — Cloudflare Tunnel hostname for cloudflared access tcp
"""
from __future__ import annotations

APP_NAME = "ndrchst Pilot"

SERVER_HOST = ""
SERVER_PORT = 25565

MC_VERSION = "1.21.1"
NEOFORGE_VERSION: str | None = None
MODPACK_URL: str | None = None
TUNNEL_HOSTNAME: str | None = None

DEFAULT_USERNAME = "Player"
SERVER_ID = ""
