"""Geyser + Floodgate auto-install for Java servers (Bedrock cross-play).

Triggered when a Java server is created with `cross_play=True`. Drops two
jars into <data_dir>/plugins/ and writes a minimal Geyser config that uses
Floodgate authentication so Bedrock players don't need a Java account.

GeyserMC API: https://download.geysermc.org/v2/projects/{project}/versions/latest/builds/latest
The `/downloads/spigot` artifact is the universal Bukkit-API jar that works
on Paper, Purpur, Spigot, and friends.
"""
from __future__ import annotations

from pathlib import Path

import httpx

GEYSER_API = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest"
FLOODGATE_API = (
    "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest"
)
DEFAULT_BEDROCK_PORT = 19132


def _spigot_artifact_url(project: str) -> str:
    return (
        f"https://download.geysermc.org/v2/projects/{project}"
        "/versions/latest/builds/latest/downloads/spigot"
    )


def _geyser_config(java_port: int, bedrock_port: int) -> str:
    return f"""\
# Generated by ndrchst. Bedrock clients connect on UDP {bedrock_port};
# Geyser proxies them to the Java server on TCP {java_port}.
bedrock:
  address: 0.0.0.0
  port: {bedrock_port}
  motd1: "Cross-play"
  motd2: "Bedrock + Java"
  server-name: "ndrchst"

remote:
  address: 127.0.0.1
  port: {java_port}
  auth-type: floodgate
  allow-password-authentication: false

floodgate-key-file: key.pem
"""


async def install_cross_play(
    data_dir: Path,
    *,
    java_port: int = 25565,
    bedrock_port: int = DEFAULT_BEDROCK_PORT,
    client: httpx.AsyncClient | None = None,
) -> None:
    """Idempotent. Overwrites existing Geyser/Floodgate jars and config."""
    own_client = client is None
    if own_client:
        client = httpx.AsyncClient(timeout=120.0)
    try:
        plugins = data_dir / "plugins"
        plugins.mkdir(parents=True, exist_ok=True)

        await _download(client, _spigot_artifact_url("geyser"), plugins / "Geyser-Spigot.jar")
        await _download(client, _spigot_artifact_url("floodgate"), plugins / "Floodgate-Spigot.jar")

        cfg_dir = plugins / "Geyser-Spigot"
        cfg_dir.mkdir(exist_ok=True)
        (cfg_dir / "config.yml").write_text(_geyser_config(java_port, bedrock_port))
    finally:
        if own_client:
            await client.aclose()


async def _download(client: httpx.AsyncClient, url: str, dest: Path) -> None:
    async with client.stream("GET", url, follow_redirects=True) as resp:
        resp.raise_for_status()
        with dest.open("wb") as f:
            async for chunk in resp.aiter_bytes(chunk_size=64 * 1024):
                f.write(chunk)
