"""Build-time config for a client drop. Generated by ndrchst's client
bundle builder per-server; edit only if you know what you're doing.

Required fields:
  APP_NAME           — displayed in the GUI title bar
  SERVER_HOST/PORT   — fallback dial target if TUNNEL_HOSTNAME isn't set
  MC_VERSION         — vanilla MC version, e.g. "1.21.1"
  DEFAULT_USERNAME   — initial username in the GUI field

Optional fields (modpack + tunnel support):
  NEOFORGE_VERSION   — pin the NeoForge build, e.g. "21.1.228"
  MODPACK_URL        — CurseForge client-pack zip URL (for overrides/* only;
                       mods are pulled from the server, see MODS_SYNC_URL)
  MODS_SYNC_URL      — base URL for the server-driven mod sync. Client pulls
                       <MODS_SYNC_URL>/mods/index.json and individual jars.
                       Default form is "<edge_url>/client/<server_id>".
  TUNNEL_HOSTNAME    — Cloudflare Tunnel hostname for cloudflared access tcp
  UPDATE_BASE_URL    — base URL for self-update (e.g. an R2 bucket fronted
                       by a custom domain). Client fetches <base>/latest.json
                       on launch; unset disables auto-update.
"""
from __future__ import annotations

APP_NAME = "ndrchst Client"

SERVER_HOST = ""
SERVER_PORT = 25565

MC_VERSION = "1.21.1"
NEOFORGE_VERSION: str | None = None
MODPACK_URL: str | None = None
MODS_SYNC_URL: str | None = None
TUNNEL_HOSTNAME: str | None = None
UPDATE_BASE_URL: str | None = None

DEFAULT_USERNAME = "Player"
SERVER_ID = ""
